title: Blogs with jekyll
author: Anandha Marthandan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My simple blog site using jekyll

# social links
twitter_username: twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
